### ISSUE TITLE
issue 1

### ISSUE THREAD

**Issue by iqbalalhadad** [aliumujib/Nibo#1]
error while opening launch location picker it has stopped

**Comment by iqbalalhadad** [comment]
java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION
                                                                                at com.google.maps.api.android.lib6.impl.ba.c(:com.google.android.gms.DynamiteModulesB@11577470:689)
                                                                                at com.google.android.gms.maps.internal.k.onTransact(:com.google.android.gms.DynamiteModulesB@11577470:141)
                                                                                at android.os.Binder.transact(Binder.java:627)
                                                                                at com.google.android.gms.internal.zzed.zzb(Unknown Source:7)
                                                                                at com.google.android.gms.maps.internal.zzg.setMyLocationEnabled(Unknown Source:9)
                                                                                at com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(Unknown Source:2)
                                                                                at com.alium.nibo.base.BaseNiboFragment.onMapReady(BaseNiboFragment.java:263)
                                                                                at com.google.android.gms.maps.zzaj.zza(Unknown Source:7)
                                                                                at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source:18)
                                                                                at android.os.Binder.transact(Binder.java:627)
                                                                                at gl.b(:com.google.android.gms.DynamiteModulesB@11577470:20)
                                                                                at com.google.android.gms.maps.internal.bf.a(:com.google.android.gms.DynamiteModulesB@11577470:5)
                                                                                at com.google.maps.api.android.lib6.impl.bc.run(:com.google.android.gms.DynamiteModulesB@11577470:5)
                                                                                at android.os.Handler.handleCallback(Handler.java:790)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by aliumujib** [comment]
Hello iqbalalhadad,

You need to add location permissions to your Android manifest file. Just add the following lines to your android manifest. 

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

I will look into handling this error so as to avoid crashes in a later version. 

Cheers,
Mujib.

**Comment by iqbalalhadad** [comment]
Thank You sir :)
