### ISSUE TITLE
The String#value field is not present on Android versions >= 6.0

### ISSUE THREAD

**Issue by freddygenicho** [aliumujib/Nibo#18]
07-29 07:47:11.970 9991-9991/ke.co.safiripesa E/art: The String#value field is not present on Android versions >= 6.0
07-29 07:48:39.418 9991-9991/ke.co.safiripesa E/NiboOriginDestinationPickerActivity: What the actual fuck?
07-29 07:48:39.958 9991-9991/ke.co.safiripesa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ke.co.safiripesa, PID: 9991
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.ViewDragHelper.processTouchEvent(android.view.MotionEvent)' on a null object reference
        at com.alium.nibo.lib.BottomSheetBehaviorGoogleMapsLike.onTouchEvent(BottomSheetBehaviorGoogleMapsLike.java:295)
        at android.support.design.widget.CoordinatorLayout.resetTouchBehaviors(CoordinatorLayout.java:389)
        at android.support.design.widget.CoordinatorLayout.onAttachedToWindow(CoordinatorLayout.java:235)
        at android.view.View.dispatchAttachedToWindow(View.java:16170)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3163)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3170)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3170)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3170)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3170)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3170)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3170)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1750)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1465)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6996)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:918)
        at android.view.Choreographer.doCallbacks(Choreographer.java:716)
        at android.view.Choreographer.doFrame(Choreographer.java:651)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:904)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)

**Comment by cse9009** [comment]
Use 'com.firebase:geofire-android:2.1.1' . May be it's version problem. It's solved for me.
