### ISSUE TITLE
GoogleMap is null

### ISSUE THREAD

**Issue by EricNjue** [aliumujib/Nibo#20]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(boolean)' on a null object reference
        at com.alium.nibo.base.BaseNiboFragment$6.onSuccess(BaseNiboFragment.java:491)
        at com.alium.nibo.base.BaseNiboFragment$6.onSuccess(BaseNiboFragment.java:483)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:27)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

how do we resolve this?

**Comment by Nyariki** [comment]
+1

**Comment by aliumujib** [comment]
@EricNjue @Nyariki I think the issue came up because I forgot to remove location updates when the activity is in background, sorry about the late replies. Will fix and update readme file accordingly.

Cheers,
Mujeeb.
